### ISSUE TITLE
Cargo could not compile dependency bitflags

### ISSUE THREAD

**Issue by ealemany** [henrybaxter/beamdpr#13]
Hi,

I have a Ubuntu 18.04 server with a GUI and i configured EGSnrc. I followed your instructions to install beamdpr.
1) install rust . # all went well 

2) install beamdpr using cargo
$ cargo install beamdpr 

I ran into an issue when i ran: $ cargo install beamdpr
Here is the output:

error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: aborting due to previous error

error: Could not compile `bitflags`.
warning: build failed, waiting for other jobs to finish...
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: aborting due to previous error

error: Could not compile `libc`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `beamdpr v0.2.3`, intermediate artifacts can be found at `/tmp/cargo-installpSoPsb`

Caused by:
  build failed

Could you tell me what i am doing wrong or what am i missing?

Thank you

**Comment by henrybaxter** [comment]
Have you tried doing `sudo apt install build-essential` on the system? Seems strange that `cc` is not available.

**Comment by ealemany** [comment]
My bad!  I made the rookie mistake to log into the wrong server. I wish i could go back in time and delete my "issue".
I apologize this post.

**Comment by henrybaxter** [comment]
All good, thanks for updating me, take care!
