### ISSUE TITLE
Negative numbers in translate

### ISSUE THREAD

**Issue by crcrewso** [henrybaxter/beamdpr#14]
Problem: 
when trying to translate in a negative direction according to the documentation
`beamdpr translate <input> <output> -y (-1.0) `
errors are output
`bash: syntax error near unexpected token '('`

System: 
Fully updated Fedora 39, with beamdpr installed via cargo

Workaround:
`beamdpr translate <input> <output> -y=-1.0`

Solution: 
Could the description page be updated to reflect the correct format for the argument for bash based installs.

**Comment by henrybaxter** [comment]
Thank you for pointing this out, the code has been updated to accept

`beamdpr translate <input> <output> -y -1.0`

And the documentation simplified, thank you!

**Comment by henrybaxter** [comment]
Fixed
